--DECLARE @CRITERIO NVARCHAR(255) = 'GASTOS ADUANEROS';
--DECLARE @CRITERIO NVARCHAR(255) = '0530';

CREATE PROCEDURE BuscarDatos
    @CRITERIO NVARCHAR(255)
AS
BEGIN
    SELECT 
        CODIGO, 
        NOMBRE, 
        COD_LIN, 
        LINEA,
        COD_SUB,
        SUBLINEA,
        COD_GRUPO,
        GRUINV_NOMBRE,
        TOTAL_ENTRADA,
        TOTAL_SALIDA,
        (TOTAL_ENTRADA - TOTAL_SALIDA) AS STOCK,
        COD_INV
    FROM (
        SELECT 
            MTMERCIA.CODIGO AS CODIGO, 
            MTMERCIA.DESCRIPCIO AS NOMBRE, 
            MTLINEA.CODLINEA AS COD_LIN, 
            MTLINEA.NOMBRE AS LINEA,
            MTSBLIN.CODSBLIN AS COD_SUB,
            MTSBLIN.NOMBRE AS SUBLINEA,
            MTGRUINV.CODGRUPO AS COD_GRUPO,
            MTGRUINV.NOMBRE AS GRUINV_NOMBRE,
            SUM(CAST(SALDOINV.ICANTIDAD AS INT)) AS TOTAL_ENTRADA,
            SUM(CAST(SALDOINV.OCANTIDAD AS INT)) AS TOTAL_SALIDA,
            SALDOINV.CODIGO AS COD_INV
        FROM 
            MTMERCIA 
        INNER JOIN 
            MTLINEA ON MTMERCIA.CODLINEA = MTLINEA.CODLINEA
        INNER JOIN 
            MTGRUINV ON MTMERCIA.CODGRUPO = MTGRUINV.CODGRUPO
        INNER JOIN 
            MTSBLIN ON MTMERCIA.CODSBLIN = MTSBLIN.CODSBLIN
        INNER JOIN
            SALDOINV ON MTMERCIA.CODIGO = SALDOINV.CODIGO
        WHERE 
            MTMERCIA.CODIGO = @CRITERIO OR 
            MTLINEA.CODLINEA = @CRITERIO OR 
            MTSBLIN.CODSBLIN = @CRITERIO OR 
            MTGRUINV.CODGRUPO = @CRITERIO OR 
            MTMERCIA.DESCRIPCIO = @CRITERIO
        GROUP BY
            MTMERCIA.CODIGO,
            MTMERCIA.DESCRIPCIO,
            MTLINEA.CODLINEA,
            MTLINEA.NOMBRE,
            MTSBLIN.CODSBLIN,
            MTSBLIN.NOMBRE,
            MTGRUINV.CODGRUPO,
            MTGRUINV.NOMBRE,
            SALDOINV.CODIGO
    ) AS Subconsulta;
END

EXEC ObtenerDatos;
EXEC BuscarDatos @CRITERIO = '1002';

DROP PROCEDURE BuscarDatos;